#AZG Python
income=float(input("what is your monthly income?:$ "))
rent=float(input("what is your monthly rent/mortgage?:$ "))
utilities=float(input("what is your monthly utilities cost?:$ "))
groceries=float(input("How much do you spend monthly on groceries?:$ "))
transportation=float(input("how much do you spend monthly on transportation?:$ "))
total=(rent+utilities+groceries+transportation)
remaining=(income-total)
print((rent/income)*100, "percent of your income is used on rent.", "$", rent)
print((utilities/income)*100, "percent of your income is used on utilities.", "$", utilities)
print((groceries/income)*100, "percent of your income is used on groceries.", "$", groceries)
print((transportation/income)*100, "percent of your income is used on transportation.", "$", transportation)
print("you have $",remaining, "left over.")